// Code generated by thriftrw-plugin-yarpc
// @generated

package barfx

import (
	fx "go.uber.org/fx"
	transport "go.uber.org/yarpc/api/transport"
	thrift "go.uber.org/yarpc/encoding/thrift"
	barserver "go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc/internal/tests/extends/barserver"
)

// ServerParams defines the dependencies for the Bar server.
//
// In addition to the required barserver.Interface handler, ServerParams
// accepts an optional value group of thrift.RegisterOption values keyed
// by thrift.FxRegisterOptionGroup ("yarpc.thrift.register_options").
// Any module in the Fx container can contribute RegisterOptions through
// this group without changing the call site of Server().
type ServerParams struct {
	fx.In

	Handler         barserver.Interface
	RegisterOptions []thrift.RegisterOption `group:"yarpc.thrift.register_options"`
}

// ServerResult defines the output of Bar server module. It provides the
// procedures of a Bar handler to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group. Dig 1.2 or newer
// must be used for this feature to work.
type ServerResult struct {
	fx.Out

	Procedures []transport.Procedure `group:"yarpcfx"`
}

// Server provides procedures for Bar to an Fx application. It expects a
// barfx.Interface to be present in the container.
//
//	fx.Provide(
//		func(h *MyBarHandler) barserver.Interface {
//			return h
//		},
//		barfx.Server(),
//	)
//
// Options supplied via the opts variadic are applied first; options
// contributed through the thrift.FxRegisterOptionGroup value group are
// appended after, so under registerConfig's last-write-wins semantics they
// override anything passed directly at construction time.
func Server(opts ...thrift.RegisterOption) interface{} {
	return func(p ServerParams) ServerResult {
		allOpts := append(opts, p.RegisterOptions...)
		procedures := barserver.New(p.Handler, allOpts...)
		return ServerResult{Procedures: procedures}
	}
}
