// Copyright (c) 2026 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package main

import (
	"path/filepath"

	"go.uber.org/thriftrw/compile"
	"go.uber.org/thriftrw/plugin"
	"go.uber.org/thriftrw/plugin/api"
)

const (
	_UUIDAnnotationKey = "auth.actor_uuid"
)

// yarpcUUIDTemplate emits an ActorUUID() accessor on every
// thriftrw-generated Service_Method_Args struct whose argument list
// has at least one path down to a field annotated with
// auth.actor_uuid. The accessor returns every reachable annotated
// value (a field that is unset contributes its zero value, "").
// The server template invokes this accessor to extract the UUIDs
// before delegating to the actorUUIDValidator.
const yarpcUUIDTemplate = `
// Code generated by thriftrw-plugin-yarpc
// @generated

package <.Name>

<range $svcName, $svc := .Services><range $fnName, $fn := $svc.Functions><$paths := uuidPathInArgs $fn><if $paths>
// ActorUUID returns the UUID strings from every field annotated with
// auth.actor_uuid that is reachable from the method arguments. A field
// that is unset contributes its zero value ("").
func (t *<goCase $svc.Name>_<goCase $fn.Name>_Args) ActorUUID() []string {
    <- $multi := gt (len $paths) 1 ->
    return []string{
    <- range $paths ->
        <- $expr := "t" ->
        <- range .Steps ->
            <- $expr = printf "%s.Get%s()" $expr (goCase .Field.Name) ->
            <- if .CastStructName ->
                <- if eq .CastImportPath "" ->
                    <- $expr = printf "(*%s)(%s)" (goCase .CastStructName) $expr ->
                <- else ->
                    <- $expr = printf "(*%s.%s)(%s)" (import .CastImportPath) (goCase .CastStructName) $expr ->
                <- end ->
            <- end ->
        <- end ->
        <- if $multi ->
            <- "\n" ->
        <- end ->
        <- if .IsTypedef>string(<end><$expr><if .IsTypedef>)<end>,
    <- end ->
    <- if $multi ->
        <- "\n" ->
    <- end ->
    }
}
<end><end><end>
`

func yarpcUUIDGenerator(data *moduleTemplateData, files map[string][]byte) error {
	// kv.thrift => .../kv/types_yarpc_uuid.go
	path := filepath.Join(data.Module.Directory, "types_yarpc_uuid.go")

	// data.CompiledModule is the result of compiling the original Thrift file.
	// Plugins do not have access to it via the API, so it is compiled once in
	// Generate and shared across generators; this generator writes extra
	// methods to types annotated with auth.actor_uuid in that Thrift file.
	compiledModule := data.CompiledModule

	templateOptions := append(templateOptions,
		plugin.TemplateFunc("uuidPathInArgs", func(fn *compile.FunctionSpec) []*uuidPath {
			return uuidPathInArgs(fn, data)
		}),
	)

	var err error
	files[path], err = plugin.GoFileFromTemplate(path, yarpcUUIDTemplate, compiledModule, templateOptions...)
	return err
}

// uuidPathStep is one hop along the path from a thriftrw-generated
// Service_Method_Args struct down to the leaf field carrying the
// annotation. Each step names a field on the parent struct of that
// step; intermediate steps reference struct-typed fields, the final
// step references the annotated string (or typedef-of-string) field.
type uuidPathStep struct {
	Field *compile.FieldSpec

	// CastStructName is the raw Thrift name of the underlying struct
	// to cast to before invoking the next step's GetXxx(). Empty
	// when no cast is needed (the field's static type is the
	// underlying struct directly, not a typedef wrapper). The
	// template applies goCase at render time to derive the Go name.
	CastStructName string

	// CastImportPath is the Go import path of the package that
	// declares the underlying struct, or "" when that package is
	// the same package the file is being generated into (no
	// qualifier needed). Only meaningful when CastStructName is set.
	CastImportPath string
}

// uuidPath is a fully resolved chain from a thriftrw-generated
// Service_Method_Args struct down to its auth.actor_uuid-annotated
// leaf field. Steps is non-empty (the last entry is the leaf,
// intermediate entries are struct-typed fields the chain walks
// through). IsTypedef reports whether the leaf field's type is a
// typedef-of-string (the chain must be wrapped in string(...) to
// match the ActorUUID() return type) versus plain string.
type uuidPath struct {
	Steps     []uuidPathStep
	IsTypedef bool
}

// findUUIDPath walks the given fields depth-first and returns every
// reachable auth.actor_uuid-annotated leaf path. The returned slice
// is empty when no valid annotation is reachable. Cycles are still
// pruned via the visited set keyed on resolved structs (so the walk
// terminates), but every annotated field on a struct is observed the
// first time the walker descends into it — including struct fields
// that also participate in a cycle through some other parent.
//
// Multiple annotated fields are allowed: the generated ActorUUID()
// accessor returns one value per reachable path, so codegen does not
// fail when a method's args reach more than one annotation.
//
// data is used only to derive the Go import path of a struct
// reached through a typedef hop in another included Thrift file (so
// the rendered cast can qualify the type with the right package
// alias); it may be nil in tests, in which case cross-package casts
// fall back to unqualified type names.
func findUUIDPath(fields compile.FieldGroup, data *moduleTemplateData) []*uuidPath {
	return walkForUUID(fields, data, make(map[*compile.StructSpec]bool))
}

func walkForUUID(fields compile.FieldGroup, data *moduleTemplateData, visited map[*compile.StructSpec]bool) []*uuidPath {
	var out []*uuidPath
	for _, f := range fields {
		if leaf := matchUUIDLeaf(f); leaf != nil {
			out = append(out, leaf)
			continue
		}
		inner, needsCast := resolveStructType(f.Type)
		if inner == nil || visited[inner] {
			continue
		}
		visited[inner] = true
		subs := walkForUUID(inner.Fields, data, visited)
		delete(visited, inner)
		step := uuidPathStep{Field: f}
		if needsCast {
			step.CastStructName = inner.Name
			step.CastImportPath = castImportPath(inner, data)
		}
		for _, sub := range subs {
			out = append(out, &uuidPath{
				Steps:     append([]uuidPathStep{step}, sub.Steps...),
				IsTypedef: sub.IsTypedef,
			})
		}
	}
	return out
}

// resolveStructType peels typedef chains to expose the underlying
// type. If that underlying type is a struct, it returns the struct
// and a flag indicating whether the input type was wrapped in one
// or more typedefs (the wrapping forces the caller to emit a Go
// pointer-conversion in the chain, since thriftrw only generates
// GetXxx() accessors on the underlying struct's named type, not on
// each typedef alias).
func resolveStructType(t compile.TypeSpec) (*compile.StructSpec, bool) {
	wrapped := false
	for {
		switch tt := t.(type) {
		case *compile.StructSpec:
			return tt, wrapped
		case *compile.TypedefSpec:
			if tt == nil {
				return nil, false
			}
			wrapped = true
			t = tt.Target
		default:
			return nil, false
		}
	}
}

// castImportPath returns the Go import path that owns the struct
// the chain has to cast through, or "" when that package is the
// same as the file being generated (no qualifier needed).
func castImportPath(ss *compile.StructSpec, data *moduleTemplateData) string {
	if ss == nil || data == nil || data.Module == nil {
		return ""
	}
	importPath := data.importPathForThriftFile(ss.ThriftFile())
	if importPath == "" || importPath == data.Module.ImportPath {
		return ""
	}
	return importPath
}

// matchUUIDLeaf decides whether f is a valid leaf for the annotation:
// it must carry the annotation and its type must be a plain string or
// a single-hop typedef of string.
func matchUUIDLeaf(f *compile.FieldSpec) *uuidPath {
	if f == nil {
		return nil
	}
	if _, ok := f.Annotations[_UUIDAnnotationKey]; !ok {
		return nil
	}
	switch t := f.Type.(type) {
	case *compile.StringSpec:
		return &uuidPath{Steps: []uuidPathStep{{Field: f}}}
	case *compile.TypedefSpec:
		if _, ok := t.Target.(*compile.StringSpec); ok {
			return &uuidPath{Steps: []uuidPathStep{{Field: f}}, IsTypedef: true}
		}
	}
	return nil
}

// uuidPathInArgs is the template-facing entry point for service
// methods. It returns every path from the synthetic
// Service_Method_Args struct to a reachable annotated leaf, or nil
// if no method argument leads to one. The generated ActorUUID()
// accessor emits one value per returned path.
func uuidPathInArgs(fn *compile.FunctionSpec, data *moduleTemplateData) []*uuidPath {
	if fn == nil {
		return nil
	}
	paths := findUUIDPath(compile.FieldGroup(fn.ArgsSpec), data)
	if len(paths) == 0 {
		return nil
	}
	return paths
}

// methodHasActorUUIDArg reports whether the given thriftrw plugin-API
// function has any argument that reaches an auth.actor_uuid
// annotation. The server template uses it to
// gate the per-method validator-call block and the per-method
// NoWire handler's validator field.
func methodHasActorUUIDArg(fn *api.Function, mod *compile.Module, serviceThriftName string) bool {
	if fn == nil {
		return false
	}
	compiled := lookupCompiledFunction(mod, serviceThriftName, fn.ThriftName)
	if compiled == nil {
		return false
	}
	return uuidPathInArgs(compiled, nil) != nil
}

// serviceHasActorUUIDMethod reports whether the given thriftrw
// plugin-API service has at least one method whose args reach an
// auth.actor_uuid annotation. The server template uses it to gate
// the service-wide handler struct's validator field and its
// initialisation inside New.
func serviceHasActorUUIDMethod(svc *api.Service, mod *compile.Module) bool {
	if svc == nil || mod == nil {
		return false
	}
	compiled := mod.Services[svc.ThriftName]
	if compiled == nil {
		return false
	}
	for _, fn := range compiled.Functions {
		if uuidPathInArgs(fn, nil) != nil {
			return true
		}
	}
	return false
}

